const kelimeHavuzu = [
    // --- A1 SEVİYE KELİMELER ---
    { en: "About", tr: "Hakkında", level: "A1" }, // [cite: 2324]
    { en: "Across", tr: "Boyunca", level: "A1" }, // [cite: 2324]
    { en: "Action", tr: "Aksiyon", level: "A1" }, // [cite: 2324]
    { en: "Activity", tr: "Aktivite", level: "A1" }, // [cite: 2324]
    { en: "Actor", tr: "Aktör", level: "A1" }, // [cite: 2324]
    { en: "Add", tr: "Eklemek", level: "A1" }, // [cite: 2324]
    { en: "Adult", tr: "Yetişkin", level: "A1" }, // [cite: 2324]
    { en: "Advice", tr: "Tavsiye", level: "A1" }, // [cite: 2324]
    { en: "Afraid", tr: "Korkmuş, korkan", level: "A1" }, // [cite: 2325]
    { en: "After", tr: "Sonra", level: "A1" }, // [cite: 2325]
    { en: "Afternoon", tr: "Öğleden sonra", level: "A1" }, // [cite: 2325]
    { en: "Again", tr: "Yeniden", level: "A1" }, // [cite: 2325]
    { en: "Age", tr: "Yaş", level: "A1" }, // [cite: 2325]
    { en: "Agree", tr: "Anlaşmak, hem fikir olmak", level: "A1" }, // [cite: 2325]
    { en: "Air", tr: "Hava", level: "A1" }, // [cite: 2325]
    { en: "Airport", tr: "Havaalanı", level: "A1" }, // [cite: 2325]
    { en: "All", tr: "Hepsi, bütünü", level: "A1" }, // [cite: 2325]
    { en: "Also", tr: "De, da, ayrıca", level: "A1" }, // [cite: 2325]
    { en: "Always", tr: "Her zaman", level: "A1" }, // [cite: 2325]
    { en: "Amazing", tr: "Harika", level: "A1" }, // [cite: 2325]
    { en: "Angry", tr: "Kızgın, öfkeli", level: "A1" }, // [cite: 2325]
    { en: "Animal", tr: "Hayvan", level: "A1" }, // [cite: 2325]
    { en: "Answer", tr: "Cevap", level: "A1" }, // [cite: 2325]
    { en: "Apartment", tr: "Apartman", level: "A1" }, // [cite: 2326]
    { en: "Apple", tr: "Elma", level: "A1" }, // [cite: 2326]
    { en: "Area", tr: "Bölge, alan", level: "A1" }, // [cite: 2326]
    { en: "Arm", tr: "Kol", level: "A1" }, // [cite: 2326]
    { en: "Around", tr: "Etrafında", level: "A1" }, // [cite: 2326]
    { en: "Arrive", tr: "Varmak, ulaşmak", level: "A1" }, // [cite: 2326]
    { en: "Art", tr: "Sanat", level: "A1" }, // [cite: 2326]
    { en: "Ask", tr: "Sormak", level: "A1" }, // [cite: 2326]
    { en: "Autumn", tr: "Sonbahar", level: "A1" }, // [cite: 2326]
    { en: "Away", tr: "Uzakta", level: "A1" }, // [cite: 2326]
    { en: "Baby", tr: "Bebek", level: "A1" }, // [cite: 2326]
    { en: "Back", tr: "Geri", level: "A1" }, // [cite: 2326]
    { en: "Bad", tr: "Kötü", level: "A1" }, // [cite: 2327]
    { en: "Bag", tr: "Çanta", level: "A1" }, // [cite: 2327]
    { en: "Ball", tr: "Top", level: "A1" }, // [cite: 2327]
    { en: "Banana", tr: "Muz", level: "A1" }, // [cite: 2327]
    { en: "Bank", tr: "Banka", level: "A1" }, // [cite: 2327]
    { en: "Bath", tr: "Banyo", level: "A1" }, // [cite: 2327]
    { en: "Beach", tr: "Sahil", level: "A1" }, // [cite: 2327]
    { en: "Beautiful", tr: "Güzel", level: "A1" }, // [cite: 2327]
    { en: "Because", tr: "Çünkü", level: "A1" }, // [cite: 2327]
    { en: "Bed", tr: "Yatak", level: "A1" }, // [cite: 2327]
    { en: "Before", tr: "Önce", level: "A1" }, // [cite: 2327]
    { en: "Begin", tr: "Başlamak", level: "A1" }, // [cite: 2327]
    { en: "Behind", tr: "Arkasında", level: "A1" }, // [cite: 2327]
    { en: "Believe", tr: "İnanmak", level: "A1" }, // [cite: 2328]
    { en: "Below", tr: "Altında", level: "A1" }, // [cite: 2328]
    { en: "Better", tr: "Daha iyi", level: "A1" }, // [cite: 2328]
    { en: "Between", tr: "Arasında", level: "A1" }, // [cite: 2328]
    { en: "Bicycle", tr: "Bisiklet", level: "A1" }, // [cite: 2328]
    { en: "Big", tr: "Büyük", level: "A1" }, // [cite: 2328]
    { en: "Bird", tr: "Kuş", level: "A1" }, // [cite: 2328]
    { en: "Birthday", tr: "Doğum günü", level: "A1" }, // [cite: 2328]
    { en: "Black", tr: "Siyah", level: "A1" }, // [cite: 2328]
    { en: "Blue", tr: "Mavi", level: "A1" }, // [cite: 2328]
    { en: "Boat", tr: "Bot, tekne", level: "A1" }, // [cite: 2328]
    { en: "Body", tr: "Vücut", level: "A1" }, // [cite: 2328]
    { en: "Book", tr: "Kitap", level: "A1" }, // [cite: 2328]
    { en: "Bored", tr: "Sıkılmış, bıkkın", level: "A1" }, // [cite: 2328]
    { en: "Boring", tr: "Sıkıcı", level: "A1" }, // [cite: 2328]
    { en: "Born", tr: "Doğmak", level: "A1" }, // [cite: 2329]
    { en: "Bottle", tr: "Şişe", level: "A1" }, // [cite: 2329]
    { en: "Box", tr: "Kutu", level: "A1" }, // [cite: 2329]
    { en: "Boy", tr: "Erkek çocuk", level: "A1" }, // [cite: 2329]
    { en: "Bread", tr: "Ekmek", level: "A1" }, // [cite: 2329]
    { en: "Break", tr: "Ara, teneffüs", level: "A1" }, // [cite: 2329]
    { en: "Breakfast", tr: "Kahvaltı", level: "A1" }, // [cite: 2329]
    { en: "Bring", tr: "Getirmek", level: "A1" }, // [cite: 2329]
    { en: "Brother", tr: "Kardeş", level: "A1" }, // [cite: 2329]
    { en: "Brown", tr: "Kahverengi", level: "A1" }, // [cite: 2329]
    { en: "Build", tr: "İnşa etmek", level: "A1" }, // [cite: 2329]
    { en: "Building", tr: "Bina", level: "A1" }, // [cite: 2329]
    { en: "Bus", tr: "Otobüs", level: "A1" }, // [cite: 2329]
    { en: "Business", tr: "İş, işletme", level: "A1" }, // [cite: 2329]
    { en: "Busy", tr: "Meşgul", level: "A1" }, // [cite: 2329]
    { en: "But", tr: "Ama", level: "A1" }, // [cite: 2329]
    { en: "Butter", tr: "Tere yağı", level: "A1" }, // [cite: 2329]
    { en: "Buy", tr: "Satın almak", level: "A1" }, // [cite: 2329]
    { en: "Call", tr: "Aramak", level: "A1" }, // [cite: 2330]
    { en: "Camera", tr: "Kamera", level: "A1" }, // [cite: 2330]
    { en: "Capital", tr: "Başkent", level: "A1" }, // [cite: 2330]
    { en: "Car", tr: "Araba", level: "A1" }, // [cite: 2330]
    { en: "Card", tr: "Kart", level: "A1" }, // [cite: 2330]
    { en: "Career", tr: "Kariyer", level: "A1" }, // [cite: 2330]
    { en: "Carrot", tr: "Havuç", level: "A1" }, // [cite: 2330]
    { en: "Carry", tr: "Taşımak", level: "A1" }, // [cite: 2330]
    { en: "Cat", tr: "Kedi", level: "A1" }, // [cite: 2330]
    { en: "Century", tr: "Yüzyıl", level: "A1" }, // [cite: 2330]
    { en: "Change", tr: "Değişmek, değiştirmek", level: "A1" }, // [cite: 2330]
    { en: "Cheap", tr: "Ucuz", level: "A1" }, // [cite: 2331]
    { en: "Check", tr: "Kontrol etmek", level: "A1" }, // [cite: 2331]
    { en: "Cheese", tr: "Peynir", level: "A1" }, // [cite: 2331]
    { en: "Chicken", tr: "Tavuk", level: "A1" }, // [cite: 2331]
    { en: "Child", tr: "Çocuk", level: "A1" }, // [cite: 2331]
    { en: "Choose", tr: "Seçmek", level: "A1" }, // [cite: 2331]
    { en: "Cinema", tr: "Sinema", level: "A1" }, // [cite: 2331]
    { en: "City", tr: "Şehir", level: "A1" }, // [cite: 2331]
    { en: "Class", tr: "Sınıf, ders", level: "A1" }, // [cite: 2331]
    { en: "Clean", tr: "Temiz", level: "A1" }, // [cite: 2331]
    { en: "Clock", tr: "Saat", level: "A1" }, // [cite: 2331]
    { en: "Close", tr: "Kapamak", level: "A1" }, // [cite: 2331]
    { en: "Clothes", tr: "Elbiseler", level: "A1" }, // [cite: 2331]
    { en: "Coat", tr: "Kaban, mont", level: "A1" }, // [cite: 2331]
    { en: "Coffee", tr: "Kahve", level: "A1" }, // [cite: 2331]
    { en: "Cold", tr: "Soğuk", level: "A1" }, // [cite: 2331]
    { en: "Colour", tr: "Renk", level: "A1" }, // [cite: 2331]
    { en: "Come", tr: "Gelmek", level: "A1" }, // [cite: 2332]
    { en: "Common", tr: "Yaygın", level: "A1" }, // [cite: 2332]
    { en: "Company", tr: "Şirket", level: "A1" }, // [cite: 2332]
    { en: "Compare", tr: "Karşılaştırmak", level: "A1" }, // [cite: 2332]
    { en: "Complete", tr: "Tamamlamak", level: "A1" }, // [cite: 2332]
    { en: "Computer", tr: "Bilgisayar", level: "A1" }, // [cite: 2332]
    { en: "Concert", tr: "Konser", level: "A1" }, // [cite: 2332]
    { en: "Conversation", tr: "Konuşma, sohbet", level: "A1" }, // [cite: 2332]
    { en: "Correct", tr: "Doğru", level: "A1" }, // [cite: 2332]
    { en: "Cost", tr: "Masraf, ücret", level: "A1" }, // [cite: 2332]
    { en: "Country", tr: "Yurt, memleket, ülke", level: "A1" }, // [cite: 2332]
    { en: "Course", tr: "Kurs", level: "A1" }, // [cite: 2332]
    { en: "Cousin", tr: "Kuzen", level: "A1" }, // [cite: 2332]
    { en: "Cow", tr: "İnek", level: "A1" }, // [cite: 2332]
    { en: "Cream", tr: "Krema", level: "A1" }, // [cite: 2332]
    { en: "Create", tr: "Yaratmak", level: "A1" }, // [cite: 2332]
    { en: "Culture", tr: "Kültür", level: "A1" }, // [cite: 2332]
    { en: "Cup", tr: "Kupa, fincan", level: "A1" }, // [cite: 2332]
    { en: "Customer", tr: "Müşteri", level: "A1" }, // [cite: 2333]
    { en: "Dance", tr: "Dans, dans etmek", level: "A1" }, // [cite: 2333]
    { en: "Dark", tr: "Karanlık", level: "A1" }, // [cite: 2333]
    { en: "Date", tr: "Zaman, randevu, tarih", level: "A1" }, // [cite: 2333]
    { en: "Day", tr: "Gün", level: "A1" }, // [cite: 2333]
    { en: "Decide", tr: "Karar vermek", level: "A1" }, // [cite: 2333]
    { en: "Delicious", tr: "Lezzetli", level: "A1" }, // [cite: 2333]
    { en: "Describe", tr: "Tanımlamak", level: "A1" }, // [cite: 2333]
    { en: "Design", tr: "Tasarım, dizayn etmek", level: "A1" }, // [cite: 2333]
    { en: "Desk", tr: "Masa", level: "A1" }, // [cite: 2333]
    { en: "Detail", tr: "Detay", level: "A1" }, // [cite: 2333]
    { en: "Dialogue", tr: "Diyalog", level: "A1" }, // [cite: 2333]
    { en: "Dictionary", tr: "Sözlük", level: "A1" }, // [cite: 2333]
    { en: "Die", tr: "Ölmek", level: "A1" }, // [cite: 2333]
    { en: "Diet", tr: "Diyet", level: "A1" }, // [cite: 2334]
    { en: "Difference", tr: "Fark", level: "A1" }, // [cite: 2334]
    { en: "Different", tr: "Farklı", level: "A1" }, // [cite: 2334]
    { en: "Difficult", tr: "Zor", level: "A1" }, // [cite: 2334]
    { en: "Dinner", tr: "Akşam yemeği", level: "A1" }, // [cite: 2334]
    { en: "Dirty", tr: "Kirli", level: "A1" }, // [cite: 2334]
    { en: "Discuss", tr: "Tartışmak", level: "A1" }, // [cite: 2334]
    { en: "Dish", tr: "Yemek", level: "A1" }, // [cite: 2334]
    { en: "Doctor", tr: "Doktor", level: "A1" }, // [cite: 2334]
    { en: "Dog", tr: "Köpek", level: "A1" }, // [cite: 2334]
    { en: "Door", tr: "Kapı", level: "A1" }, // [cite: 2334]
    { en: "Draw", tr: "Çizmek", level: "A1" }, // [cite: 2334]
    { en: "Dress", tr: "Giysi, giyinmek", level: "A1" }, // [cite: 2334]
    { en: "Drink", tr: "İçmek", level: "A1" }, // [cite: 2334]
    { en: "Drive", tr: "Sürmek", level: "A1" }, // [cite: 2334]
    { en: "Driver", tr: "Sürücü, şoför", level: "A1" }, // [cite: 2334]
    { en: "Early", tr: "Erken", level: "A1" }, // [cite: 2335]
    { en: "East", tr: "Doğu", level: "A1" }, // [cite: 2335]
    { en: "Easy", tr: "Kolay", level: "A1" }, // [cite: 2335]
    { en: "Eat", tr: "Yemek", level: "A1" }, // [cite: 2335]
    { en: "Egg", tr: "Yumurta", level: "A1" }, // [cite: 2335]
    { en: "Email", tr: "Email", level: "A1" }, // [cite: 2335]
    { en: "End", tr: "Son, bitmek", level: "A1" }, // [cite: 2335]
    { en: "Enjoy", tr: "Tadını çıkarmak, zevk almak", level: "A1" }, // [cite: 2335]
    { en: "Evening", tr: "Akşam", level: "A1" }, // [cite: 2335]
    { en: "Event", tr: "Olay, vakıa", level: "A1" }, // [cite: 2335]
    { en: "Exam", tr: "Sınav", level: "A1" }, // [cite: 2336]
    { en: "Excited", tr: "Heyecanlı", level: "A1" }, // [cite: 2336]
    { en: "Exciting", tr: "Heyecan verici", level: "A1" }, // [cite: 2336]
    { en: "Exercise", tr: "Egzersiz, alıştırma", level: "A1" }, // [cite: 2336]
    { en: "Expensive", tr: "Pahalı", level: "A1" }, // [cite: 2336]
    { en: "Explain", tr: "Açıklamak", level: "A1" }, // [cite: 2336]
    { en: "Extra", tr: "Ekstra", level: "A1" }, // [cite: 2336]
    { en: "Eye", tr: "Göz", level: "A1" }, // [cite: 2336]
    { en: "Face", tr: "Yüz", level: "A1" }, // [cite: 2336]
    { en: "Fact", tr: "Gerçek, vak'a", level: "A1" }, // [cite: 2336]
    { en: "Fall", tr: "Düşmek", level: "A1" }, // [cite: 2336]
    { en: "False", tr: "Hatalı, yanlış", level: "A1" }, // [cite: 2336]
    { en: "Family", tr: "Aile", level: "A1" }, // [cite: 2336]
    { en: "Famous", tr: "Ünlü", level: "A1" }, // [cite: 2336]
    { en: "Far", tr: "Uzak", level: "A1" }, // [cite: 2336]
    { en: "Farmer", tr: "Çiftçi", level: "A1" }, // [cite: 2336]
    { en: "Fast", tr: "Hızlı", level: "A1" }, // [cite: 2336]
    { en: "Fat", tr: "Şişman", level: "A1" }, // [cite: 2337]
    { en: "Father", tr: "Baba", level: "A1" }, // [cite: 2337]
    { en: "Feeling", tr: "His", level: "A1" }, // [cite: 2337]
    { en: "Festival", tr: "Festival", level: "A1" }, // [cite: 2337]
    { en: "Fill", tr: "Doldurmak", level: "A1" }, // [cite: 2337]
    { en: "Film", tr: "Film", level: "A1" }, // [cite: 2337]
    { en: "Final", tr: "Final", level: "A1" }, // [cite: 2337]
    { en: "Find", tr: "Bulmak", level: "A1" }, // [cite: 2337]
    { en: "Fine", tr: "İyi, güzel", level: "A1" }, // [cite: 2337]
    { en: "Fire", tr: "Ateş", level: "A1" }, // [cite: 2337]
    { en: "Fish", tr: "Balık", level: "A1" }, // [cite: 2337]
    { en: "Flat", tr: "Daire, apartman katı", level: "A1" }, // [cite: 2337]
    { en: "Flight", tr: "Uçuş", level: "A1" }, // [cite: 2337]
    { en: "Floor", tr: "Zemin, kat", level: "A1" }, // [cite: 2338]
    { en: "Flower", tr: "Çiçek", level: "A1" }, // [cite: 2338]
    { en: "Fly", tr: "Uçmak", level: "A1" }, // [cite: 2338]
    { en: "Follow", tr: "Takip etmek", level: "A1" }, // [cite: 2338]
    { en: "Food", tr: "Yemek, yiyecek", level: "A1" }, // [cite: 2338]
    { en: "Foot", tr: "Ayak", level: "A1" }, // [cite: 2338]
    { en: "Football", tr: "Futbol", level: "A1" }, // [cite: 2338]
    { en: "Forget", tr: "Unutmak", level: "A1" }, // [cite: 2338]
    { en: "Form", tr: "Form, şekil almak", level: "A1" }, // [cite: 2338]
    { en: "Free", tr: "Özgür, ücretsiz", level: "A1" }, // [cite: 2338]
    { en: "Friend", tr: "Arkadaş", level: "A1" }, // [cite: 2338]
    { en: "Friendly", tr: "Arkadaşça, dostça", level: "A1" }, // [cite: 2338]
    { en: "Front", tr: "Ön, cephe", level: "A1" }, // [cite: 2338]
    { en: "Fruit", tr: "Meyve", level: "A1" }, // [cite: 2339]
    { en: "Full", tr: "Dolu, tok", level: "A1" }, // [cite: 2339]
    { en: "Fun", tr: "Eğlence", level: "A1" }, // [cite: 2339]
    { en: "Funny", tr: "Eğlenceli", level: "A1" }, // [cite: 2339]
    { en: "Future", tr: "Gelecek", level: "A1" }, // [cite: 2339]
    { en: "Game", tr: "Oyun", level: "A1" }, // [cite: 2339]
    { en: "Garden", tr: "Bahçe", level: "A1" }, // [cite: 2339]
    { en: "Geography", tr: "Coğrafya", level: "A1" }, // [cite: 2339]
    { en: "Get", tr: "Almak, elde etmek", level: "A1" }, // [cite: 2339]
    { en: "Girl", tr: "Kız", level: "A1" }, // [cite: 2339]
    { en: "Give", tr: "Vermek", level: "A1" }, // [cite: 2339]
    { en: "Glass", tr: "Bardak", level: "A1" }, // [cite: 2339]
    { en: "Go", tr: "Gitmek", level: "A1" }, // [cite: 2339]
    { en: "Good", tr: "İyi, güzel", level: "A1" }, // [cite: 2339]
    { en: "Great", tr: "Harika", level: "A1" }, // [cite: 2339]
    { en: "Green", tr: "Yeşil", level: "A1" }, // [cite: 2340]
    { en: "Group", tr: "Grup", level: "A1" }, // [cite: 2340]
    { en: "Grow", tr: "Büyümek, gelişmek", level: "A1" }, // [cite: 2340]
    { en: "Guitar", tr: "Gitar", level: "A1" }, // [cite: 2340]
    { en: "Gym", tr: "Spor salonu", level: "A1" }, // [cite: 2340]
    { en: "Hair", tr: "Saç", level: "A1" }, // [cite: 2340]
    { en: "Hand", tr: "El", level: "A1" }, // [cite: 2340]
    { en: "Happen", tr: "Olmak, meydana gelmek", level: "A1" }, // [cite: 2340]
    { en: "Happy", tr: "Mutlu", level: "A1" }, // [cite: 2340]
    { en: "Hard", tr: "Zor", level: "A1" }, // [cite: 2340]
    { en: "Hat", tr: "Şapka", level: "A1" }, // [cite: 2340]
    { en: "Hate", tr: "Nefret etmek", level: "A1" }, // [cite: 2340]
    { en: "Have", tr: "Sahip olmak", level: "A1" }, // [cite: 2340]
    { en: "Head", tr: "Kafa, baş", level: "A1" }, // [cite: 2340]
    { en: "Health", tr: "Sağlık", level: "A1" }, // [cite: 2340]
    { en: "Healthy", tr: "Sağlıklı", level: "A1" }, // [cite: 2340]
    { en: "Hear", tr: "Duymak", level: "A1" }, // [cite: 2341]
    { en: "Help", tr: "Yardım etmek", level: "A1" }, // [cite: 2341]
    { en: "High", tr: "Yüksek", level: "A1" }, // [cite: 2341]
    { en: "History", tr: "Tarih", level: "A1" }, // [cite: 2341]
    { en: "Hobby", tr: "Hobi", level: "A1" }, // [cite: 2341]
    { en: "Holiday", tr: "Tatil", level: "A1" }, // [cite: 2341]
    { en: "Home", tr: "Ev", level: "A1" }, // [cite: 2341]
    { en: "Homework", tr: "Ev ödevi", level: "A1" }, // [cite: 2341]
    { en: "Horse", tr: "At", level: "A1" }, // [cite: 2341]
    { en: "Hospital", tr: "Hastahane", level: "A1" }, // [cite: 2341]
    { en: "Hot", tr: "Sıcak", level: "A1" }, // [cite: 2341]
    { en: "Hotel", tr: "Hotel", level: "A1" }, // [cite: 2341]
    { en: "Hour", tr: "Saat", level: "A1" }, // [cite: 2341]
    { en: "House", tr: "Ev", level: "A1" }, // [cite: 2342]
    { en: "Hungry", tr: "Aç", level: "A1" }, // [cite: 2342]
    { en: "Husband", tr: "Koca", level: "A1" }, // [cite: 2342]
    { en: "Ice", tr: "Buz", level: "A1" }, // [cite: 2342]
    { en: "Idea", tr: "İdea, düşünce, fikir", level: "A1" }, // [cite: 2342]
    { en: "Imagine", tr: "Hayal etmek", level: "A1" }, // [cite: 2342]
    { en: "Important", tr: "Önemli", level: "A1" }, // [cite: 2342]
    { en: "Improve", tr: "Geliştirmek", level: "A1" }, // [cite: 2342]
    { en: "Include", tr: "İçermek", level: "A1" }, // [cite: 2342]
    { en: "Information", tr: "Bilgi", level: "A1" }, // [cite: 2342]
    { en: "Interest", tr: "İlgi, ilgilenmek", level: "A1" }, // [cite: 2342]
    { en: "Interested", tr: "İlginç", level: "A1" }, // [cite: 2342]
    { en: "Interesting", tr: "İlginç", level: "A1" }, // [cite: 2342]
    { en: "Internet", tr: "İnternet", level: "A1" }, // [cite: 2343]
    { en: "Interview", tr: "Görüşme, mülakat", level: "A1" }, // [cite: 2343]
    { en: "Introduce", tr: "Tanıtmak", level: "A1" }, // [cite: 2343]
    { en: "Island", tr: "Ada", level: "A1" }, // [cite: 2343]
    { en: "Jacket", tr: "Ceket", level: "A1" }, // [cite: 2343]
    { en: "Jeans", tr: "Kot pantolon", level: "A1" }, // [cite: 2343]
    { en: "Job", tr: "İş", level: "A1" }, // [cite: 2343]
    { en: "Join", tr: "Katılmak", level: "A1" }, // [cite: 2343]
    { en: "Journey", tr: "Seyahat, gezi", level: "A1" }, // [cite: 2343]
    { en: "Juice", tr: "Meyve suyu", level: "A1" }, // [cite: 2343]
    { en: "Keep", tr: "Tutmak", level: "A1" }, // [cite: 2343]
    { en: "Key", tr: "Anahtar", level: "A1" }, // [cite: 2343]
    { en: "Kitchen", tr: "Mutfak", level: "A1" }, // [cite: 2344]
    { en: "Know", tr: "Bilmek", level: "A1" }, // [cite: 2344]
    { en: "Language", tr: "Dil", level: "A1" }, // [cite: 2344]
    { en: "Large", tr: "Geniş", level: "A1" }, // [cite: 2344]
    { en: "Late", tr: "Geç", level: "A1" }, // [cite: 2344]
    { en: "Laugh", tr: "Gülme, gülmek", level: "A1" }, // [cite: 2344]
    { en: "Left", tr: "Sol", level: "A1" }, // [cite: 2344]
    { en: "Leg", tr: "Bacak, ayak", level: "A1" }, // [cite: 2344]
    { en: "Lesson", tr: "Ders", level: "A1" }, // [cite: 2344]
    { en: "Let", tr: "İzin vermek, müsaade etmek", level: "A1" }, // [cite: 2344]
    { en: "Letter", tr: "Mektup", level: "A1" }, // [cite: 2344]
    { en: "Library", tr: "Kütüphane", level: "A1" }, // [cite: 2344]
    { en: "Lie", tr: "Yalan söylemek", level: "A1" }, // [cite: 2344]
    { en: "Life", tr: "Hayat, yaşam", level: "A1" }, // [cite: 2344]
    { en: "Light", tr: "Işık", level: "A1" }, // [cite: 2344]
    { en: "Line", tr: "Satır, hat, çizgi", level: "A1" }, // [cite: 2344]
    { en: "Lion", tr: "Aslan", level: "A1" }, // [cite: 2345]
    { en: "List", tr: "Liste, listelemek", level: "A1" }, // [cite: 2345]
    { en: "Listen", tr: "Dinlemek", level: "A1" }, // [cite: 2345]
    { en: "Little", tr: "Küçük", level: "A1" }, // [cite: 2345]
    { en: "Live", tr: "Yaşamak", level: "A1" }, // [cite: 2345]
    { en: "Local", tr: "Yerel", level: "A1" }, // [cite: 2345]
    { en: "Long", tr: "Uzun", level: "A1" }, // [cite: 2345]
    { en: "Look", tr: "Bakmak", level: "A1" }, // [cite: 2345]
    { en: "Lose", tr: "Kaybetmek", level: "A1" }, // [cite: 2345]
    { en: "Love", tr: "Sevmek, aşk", level: "A1" }, // [cite: 2345]
    { en: "Lunch", tr: "Öğle yemeği", level: "A1" }, // [cite: 2345]
    { en: "Machine", tr: "Makine", level: "A1" }, // [cite: 2345]
    { en: "Magazine", tr: "Dergi", level: "A1" }, // [cite: 2345]
    { en: "Main", tr: "Esas, başlıca, ana", level: "A1" }, // [cite: 2345]
    { en: "Make", tr: "Yapmak", level: "A1" }, // [cite: 2345]
    { en: "Man", tr: "Adam, erkek", level: "A1" }, // [cite: 2345]
    { en: "Many", tr: "Çok", level: "A1" }, // [cite: 2345]
    { en: "Map", tr: "Harita", level: "A1" }, // [cite: 2345]
    { en: "Market", tr: "Market", level: "A1" }, // [cite: 2346]
    { en: "Married", tr: "Evli", level: "A1" }, // [cite: 2346]
    { en: "Maybe", tr: "Belki", level: "A1" }, // [cite: 2346]
    { en: "Meal", tr: "Öğün", level: "A1" }, // [cite: 2346]
    { en: "Mean", tr: "Demek, istemek, kastetmek", level: "A1" }, // [cite: 2346]
    { en: "Meaning", tr: "Anlam, mana", level: "A1" }, // [cite: 2346]
    { en: "Meat", tr: "Et", level: "A1" }, // [cite: 2346]
    { en: "Meet", tr: "Tanışmak, buluşmak", level: "A1" }, // [cite: 2346]
    { en: "Meeting", tr: "Buluşma", level: "A1" }, // [cite: 2346]
    { en: "Member", tr: "Üye", level: "A1" }, // [cite: 2346]
    { en: "Menu", tr: "Menü", level: "A1" }, // [cite: 2346]
    { en: "Message", tr: "Mesaj", level: "A1" }, // [cite: 2346]
    { en: "Midnight", tr: "Gece yarısı", level: "A1" }, // [cite: 2346]
    { en: "Milk", tr: "Süt", level: "A1" }, // [cite: 2346]
    { en: "Minute", tr: "Dakika", level: "A1" }, // [cite: 2346]
    { en: "Miss", tr: "Kaçırmak, özlemek", level: "A1" }, // [cite: 2347]
    { en: "Mistake", tr: "Hata, yanlış", level: "A1" }, // [cite: 2347]
    { en: "Model", tr: "Model", level: "A1" }, // [cite: 2347]
    { en: "Modern", tr: "Modern, yeni", level: "A1" }, // [cite: 2347]
    { en: "Moment", tr: "An", level: "A1" }, // [cite: 2347]
    { en: "Money", tr: "Para", level: "A1" }, // [cite: 2347]
    { en: "Month", tr: "Ay", level: "A1" }, // [cite: 2347]
    { en: "More", tr: "Daha", level: "A1" }, // [cite: 2347]
    { en: "Morning", tr: "Sabah", level: "A1" }, // [cite: 2347]
    { en: "Mother", tr: "Anne", level: "A1" }, // [cite: 2347]
    { en: "Mountain", tr: "Dağ", level: "A1" }, // [cite: 2347]
    { en: "Mouse", tr: "Fare", level: "A1" }, // [cite: 2347]
    { en: "Mouth", tr: "Ağız", level: "A1" }, // [cite: 2347]
    { en: "Move", tr: "Hareket etmek", level: "A1" }, // [cite: 2347]
    { en: "Movie", tr: "Film", level: "A1" }, // [cite: 2347]
    { en: "Much", tr: "Fazla, çok", level: "A1" }, // [cite: 2347]
    { en: "Museum", tr: "Müze", level: "A1" }, // [cite: 2347]
    { en: "Music", tr: "Müzik", level: "A1" }, // [cite: 2348]
    { en: "Must", tr: "Zorunluluk, gereklilik", level: "A1" }, // [cite: 2348]
    { en: "Name", tr: "İsim, isimlendirmek", level: "A1" }, // [cite: 2348]
    { en: "Natural", tr: "Doğal", level: "A1" }, // [cite: 2348]
    { en: "Near", tr: "Yakın, yakınında", level: "A1" }, // [cite: 2348]
    { en: "Need", tr: "Gerekmek, ihtiyacı olmak", level: "A1" }, // [cite: 2348]
    { en: "Negative", tr: "Olumsuz", level: "A1" }, // [cite: 2348]
    { en: "Neighbour", tr: "Komşu", level: "A1" }, // [cite: 2348]
    { en: "Never", tr: "Asla", level: "A1" }, // [cite: 2348]
    { en: "New", tr: "Yeni", level: "A1" }, // [cite: 2348]
    { en: "News", tr: "Haberler", level: "A1" }, // [cite: 2348]
    { en: "Newspaper", tr: "Gazete", level: "A1" }, // [cite: 2348]
    { en: "Next", tr: "Sıradaki, gelecek", level: "A1" }, // [cite: 2348]
    { en: "Nice", tr: "İyi, hoş, güzel", level: "A1" }, // [cite: 2348]
    { en: "Night", tr: "Gece", level: "A1" }, // [cite: 2348]
    { en: "No one", tr: "Hiç kimse", level: "A1" }, // [cite: 2349]
    { en: "Nobody", tr: "Hiç kimse", level: "A1" }, // [cite: 2349]
    { en: "Nose", tr: "Burun", level: "A1" }, // [cite: 2349]
    { en: "Note", tr: "Not", level: "A1" }, // [cite: 2349]
    { en: "Nothing", tr: "Hiçbir şey", level: "A1" }, // [cite: 2349]
    { en: "Now", tr: "Şimdi, şuan", level: "A1" }, // [cite: 2349]
    { en: "Number", tr: "Numara", level: "A1" }, // [cite: 2349]
    { en: "Nurse", tr: "Hemşire", level: "A1" }, // [cite: 2349]
    { en: "Object", tr: "Obje, nesne", level: "A1" }, // [cite: 2349]
    { en: "Office", tr: "Ofis", level: "A1" }, // [cite: 2349]
    { en: "Often", tr: "Sıklıkla", level: "A1" }, // [cite: 2349]
    { en: "Old", tr: "Eski", level: "A1" }, // [cite: 2349]
    { en: "Onion", tr: "Soğan", level: "A1" }, // [cite: 2350]
    { en: "Online", tr: "Online", level: "A1" }, // [cite: 2350]
    { en: "Only", tr: "Sadece", level: "A1" }, // [cite: 2350]
    { en: "Open", tr: "Açık, açmak", level: "A1" }, // [cite: 2350]
    { en: "Opinion", tr: "Görüş, fikir", level: "A1" }, // [cite: 2350]
    { en: "Opposite", tr: "Karşı, zıt, aksi", level: "A1" }, // [cite: 2350]
    { en: "Orange", tr: "Portakal", level: "A1" }, // [cite: 2350]
    { en: "Order", tr: "Sipariş, sipariş vermek", level: "A1" }, // [cite: 2350]
    { en: "Other", tr: "Diğeri, başkası", level: "A1" }, // [cite: 2350]
    { en: "Outside", tr: "Dışarı", level: "A1" }, // [cite: 2350]
    { en: "Over", tr: "Üstünde, üzerinde", level: "A1" }, // [cite: 2350]
    { en: "Page", tr: "Sayfa", level: "A1" }, // [cite: 2350]
    { en: "Paint", tr: "Boya, boyamak", level: "A1" }, // [cite: 2350]
    { en: "Painting", tr: "Tablo, resim", level: "A1" }, // [cite: 2350]
    { en: "Pair", tr: "Çift, eş", level: "A1" }, // [cite: 2351]
    { en: "Paper", tr: "Sayfa", level: "A1" }, // [cite: 2351]
    { en: "Paragraph", tr: "Paragraf", level: "A1" }, // [cite: 2351]
    { en: "Parent", tr: "Ebeveyn", level: "A1" }, // [cite: 2351]
    { en: "Park", tr: "Park", level: "A1" }, // [cite: 2351]
    { en: "Part", tr: "Bölüm, part", level: "A1" }, // [cite: 2351]
    { en: "Partner", tr: "Partner", level: "A1" }, // [cite: 2351]
    { en: "Party", tr: "Parti", level: "A1" }, // [cite: 2351]
    { en: "Passport", tr: "Pasaport", level: "A1" }, // [cite: 2351]
    { en: "Past", tr: "Geçmiş", level: "A1" }, // [cite: 2351]
    { en: "Pay", tr: "Ödemek", level: "A1" }, // [cite: 2351]
    { en: "Pen", tr: "Dolma kalem", level: "A1" }, // [cite: 2351]
    { en: "Pencil", tr: "Kurşun kalem", level: "A1" }, // [cite: 2351]
    { en: "People", tr: "İnsanlar, halk", level: "A1" }, // [cite: 2351]
    { en: "Pepper", tr: "Biber", level: "A1" }, // [cite: 2351]
    { en: "Perfect", tr: "Harika", level: "A1" }, // [cite: 2351]
    { en: "Period", tr: "Periyot", level: "A1" }, // [cite: 2351]
    { en: "Person", tr: "İnsan, kişi", level: "A1" }, // [cite: 2351]
    { en: "Personal", tr: "Kişisel, şahsi", level: "A1" }, // [cite: 2351]
    { en: "Phone", tr: "Telefon", level: "A1" }, // [cite: 2351]
    { en: "Photo", tr: "Foto, resim", level: "A1" }, // [cite: 2352]
    { en: "Photograph", tr: "Fotoğraf", level: "A1" }, // [cite: 2352]
    { en: "Phrase", tr: "İbare, tabir", level: "A1" }, // [cite: 2352]
    { en: "Piano", tr: "Piyano", level: "A1" }, // [cite: 2352]
    { en: "Picture", tr: "Resim", level: "A1" }, // [cite: 2352]
    { en: "Piece", tr: "Tane, parça", level: "A1" }, // [cite: 2352]
    { en: "Pig", tr: "Domuz", level: "A1" }, // [cite: 2352]
    { en: "Pink", tr: "Pembe", level: "A1" }, // [cite: 2352]
    { en: "Place", tr: "Yer, mekan", level: "A1" }, // [cite: 2352]
    { en: "Plan", tr: "Plan, planlamak", level: "A1" }, // [cite: 2352]
    { en: "Plane", tr: "Uçak", level: "A1" }, // [cite: 2352]
    { en: "Plant", tr: "Bitki", level: "A1" }, // [cite: 2352]
    { en: "Play", tr: "Oyun, oynamak", level: "A1" }, // [cite: 2352]
    { en: "Player", tr: "Oyuncu", level: "A1" }, // [cite: 2352]
    { en: "Please", tr: "Lütfen", level: "A1" }, // [cite: 2352]
    { en: "Point", tr: "Nokta, puan", level: "A1" }, // [cite: 2352]
    { en: "Police", tr: "Polis", level: "A1" }, // [cite: 2352]
    { en: "Policeman", tr: "Polis", level: "A1" }, // [cite: 2352]
    { en: "Pool", tr: "Havuz", level: "A1" }, // [cite: 2352]
    { en: "Poor", tr: "Fakir", level: "A1" }, // [cite: 2352]
    { en: "Popular", tr: "Popüler", level: "A1" }, // [cite: 2353]
    { en: "Positive", tr: "Pozitif", level: "A1" }, // [cite: 2353]
    { en: "Possible", tr: "Mümkün, olabilir", level: "A1" }, // [cite: 2353]
    { en: "Post", tr: "Makam, posta, postalamak", level: "A1" }, // [cite: 2353]
    { en: "Potato", tr: "Patates", level: "A1" }, // [cite: 2353]
    { en: "Practice", tr: "Egzersiz, idman", level: "A1" }, // [cite: 2353]
    { en: "Practise", tr: "Alıştırma yapmak", level: "A1" }, // [cite: 2353]
    { en: "Prefer", tr: "Tercih etmek", level: "A1" }, // [cite: 2353]
    { en: "Prepare", tr: "Hazırlamak", level: "A1" }, // [cite: 2353]
    { en: "Present", tr: "Şimdiki zaman", level: "A1" }, // [cite: 2353]
    { en: "Pretty", tr: "Hoş, güzel, şirin, tatlı", level: "A1" }, // [cite: 2353]
    { en: "Price", tr: "Fiyat", level: "A1" }, // [cite: 2353]
    { en: "Probably", tr: "Muhtemelen", level: "A1" }, // [cite: 2353]
    { en: "Problem", tr: "Problem", level: "A1" }, // [cite: 2353]
    { en: "Product", tr: "Ürün", level: "A1" }, // [cite: 2353]
    { en: "Programme", tr: "Program", level: "A1" }, // [cite: 2353]
    { en: "Project", tr: "Proje", level: "A1" }, // [cite: 2353]
    { en: "Purple", tr: "Mor", level: "A1" }, // [cite: 2353]
    { en: "Put", tr: "Koymak", level: "A1" }, // [cite: 2353]
    { en: "Quarter", tr: "Çeyrek", level: "A1" }, // [cite: 2354]
    { en: "Question", tr: "Soru", level: "A1" }, // [cite: 2354]
    { en: "Quick", tr: "Hızlı", level: "A1" }, // [cite: 2354]
    { en: "Quickly", tr: "Hızlıca", level: "A1" }, // [cite: 2354]
    { en: "Quiet", tr: "Sakin, sessiz", level: "A1" }, // [cite: 2354]
    { en: "Quite", tr: "Epeyce, oldukça", level: "A1" }, // [cite: 2354]
    { en: "Radio", tr: "Radyo", level: "A1" }, // [cite: 2354]
    { en: "Rain", tr: "Yağmur, yağmur yağmak", level: "A1" }, // [cite: 2354]
    { en: "Read", tr: "Okumak", level: "A1" }, // [cite: 2354]
    { en: "Reader", tr: "Okuyucu", level: "A1" }, // [cite: 2354]
    { en: "Reading", tr: "Okuma", level: "A1" }, // [cite: 2354]
    { en: "Ready", tr: "Hazır", level: "A1" }, // [cite: 2354]
    { en: "Real", tr: "Gerçek", level: "A1" }, // [cite: 2354]
    { en: "Really", tr: "Gerçekten", level: "A1" }, // [cite: 2354]
    { en: "Reason", tr: "Sebep", level: "A1" }, // [cite: 2354]
    { en: "Red", tr: "Kırmızı", level: "A1" }, // [cite: 2354]
    { en: "Relax", tr: "Rahatlamak, dinlenmek", level: "A1" }, // [cite: 2354]
    { en: "Remember", tr: "Hatırlamak", level: "A1" }, // [cite: 2354]
    { en: "Repeat", tr: "Tekrar etmek", level: "A1" }, // [cite: 2354]
    { en: "Report", tr: "Rapor", level: "A1" }, // [cite: 2354]
    { en: "Restaurant", tr: "Restoran", level: "A1" }, // [cite: 2355]
    { en: "Result", tr: "Sonuç", level: "A1" }, // [cite: 2355]
    { en: "Return", tr: "Geri dönmek", level: "A1" }, // [cite: 2355]
    { en: "Rice", tr: "Pirinç", level: "A1" }, // [cite: 2355]
    { en: "Rich", tr: "Zengin", level: "A1" }, // [cite: 2355]
    { en: "Ride", tr: "Sürmek", level: "A1" }, // [cite: 2355]
    { en: "Right", tr: "Doğru", level: "A1" }, // [cite: 2355]
    { en: "River", tr: "Nehir", level: "A1" }, // [cite: 2355]
    { en: "Road", tr: "Yol", level: "A1" }, // [cite: 2355]
    { en: "Room", tr: "Oda", level: "A1" }, // [cite: 2355]
    { en: "Routine", tr: "Rutin", level: "A1" }, // [cite: 2355]
    { en: "Rule", tr: "Kural", level: "A1" }, // [cite: 2355]
    { en: "Run", tr: "Koşmak", level: "A1" }, // [cite: 2355]
    { en: "Sad", tr: "Üzgün", level: "A1" }, // [cite: 2355]
    { en: "Salad", tr: "Salata", level: "A1" }, // [cite: 2355]
    { en: "Salt", tr: "Tuz", level: "A1" }, // [cite: 2355]
    { en: "Same", tr: "Aynı", level: "A1" }, // [cite: 2355]
    { en: "Sandwich", tr: "Sandviç", level: "A1" }, // [cite: 2355]
    { en: "Say", tr: "Söylemek", level: "A1" }, // [cite: 2355]
    { en: "School", tr: "Okul", level: "A1" }, // [cite: 2356]
    { en: "Science", tr: "Bilim", level: "A1" }, // [cite: 2356]
    { en: "Scientist", tr: "Bilim adamı", level: "A1" }, // [cite: 2356]
    { en: "Sea", tr: "Deniz", level: "A1" }, // [cite: 2356]
    { en: "Second", tr: "İkinci", level: "A1" }, // [cite: 2356]
    { en: "Section", tr: "Kesit, bölüm, kısım", level: "A1" }, // [cite: 2356]
    { en: "See", tr: "Görmek", level: "A1" }, // [cite: 2356]
    { en: "Sell", tr: "Satmak", level: "A1" }, // [cite: 2356]
    { en: "Send", tr: "Göndermek", level: "A1" }, // [cite: 2356]
    { en: "Sentence", tr: "Cümle", level: "A1" }, // [cite: 2356]
    { en: "Share", tr: "Paylaşmak", level: "A1" }, // [cite: 2356]
    { en: "Sheep", tr: "Koyun", level: "A1" }, // [cite: 2356]
    { en: "Shirt", tr: "Gömlek", level: "A1" }, // [cite: 2356]
    { en: "Shoe", tr: "Ayakkabı", level: "A1" }, // [cite: 2356]
    { en: "Shop", tr: "Alışveriş, alışveriş yapmak", level: "A1" }, // [cite: 2356]
    { en: "Shopping", tr: "Alışveriş yapma", level: "A1" }, // [cite: 2357]
    { en: "Short", tr: "Kısa", level: "A1" }, // [cite: 2357]
    { en: "Should", tr: "Gerekmek, -meli, -malı", level: "A1" }, // [cite: 2357]
    { en: "Show", tr: "Göstermek", level: "A1" }, // [cite: 2357]
    { en: "Shower", tr: "Duş", level: "A1" }, // [cite: 2357]
    { en: "Sick", tr: "Hasta", level: "A1" }, // [cite: 2357]
    { en: "Similar", tr: "Benzer", level: "A1" }, // [cite: 2357]
    { en: "Sing", tr: "Şarkı söylemek", level: "A1" }, // [cite: 2357]
    { en: "Singer", tr: "Şarkıcı", level: "A1" }, // [cite: 2357]
    { en: "Sister", tr: "Kız kardeş, hemşire", level: "A1" }, // [cite: 2357]
    { en: "Sit", tr: "Oturmak", level: "A1" }, // [cite: 2357]
    { en: "Situation", tr: "Durum", level: "A1" }, // [cite: 2357]
    { en: "Skill", tr: "Yetenek", level: "A1" }, // [cite: 2357]
    { en: "Skirt", tr: "Etek", level: "A1" }, // [cite: 2357]
    { en: "Sleep", tr: "Uyumak", level: "A1" }, // [cite: 2357]
    { en: "Slow", tr: "Yavaş", level: "A1" }, // [cite: 2357]
    { en: "Small", tr: "Küçük", level: "A1" }, // [cite: 2357]
    { en: "Snake", tr: "Yılan", level: "A1" }, // [cite: 2358]
    { en: "Snow", tr: "Kar, kar yağmak", level: "A1" }, // [cite: 2358]
    { en: "Somebody", tr: "Birisi", level: "A1" }, // [cite: 2358]
    { en: "Someone", tr: "Birisi", level: "A1" }, // [cite: 2358]
    { en: "Something", tr: "Bir şey", level: "A1" }, // [cite: 2358]
    { en: "Sometimes", tr: "Bazen", level: "A1" }, // [cite: 2358]
    { en: "Son", tr: "Oğul", level: "A1" }, // [cite: 2358]
    { en: "Song", tr: "Şarkı", level: "A1" }, // [cite: 2358]
    { en: "Soon", tr: "Yakında", level: "A1" }, // [cite: 2358]
    { en: "Sound", tr: "Ses", level: "A1" }, // [cite: 2358]
    { en: "Soup", tr: "Çorba", level: "A1" }, // [cite: 2358]
    { en: "South", tr: "Güney", level: "A1" }, // [cite: 2358]
    { en: "Space", tr: "Alan, mekan, uzay", level: "A1" }, // [cite: 2358]
    { en: "Speak", tr: "Konuşmak", level: "A1" }, // [cite: 2358]
    { en: "Special", tr: "Özel", level: "A1" }, // [cite: 2358]
    { en: "Spell", tr: "Hecelemek", level: "A1" }, // [cite: 2358]
    { en: "Spelling", tr: "Heceleme", level: "A1" }, // [cite: 2358]
    { en: "Spend", tr: "Harcamak", level: "A1" }, // [cite: 2358]
    { en: "Sport", tr: "Spor", level: "A1" }, // [cite: 2359]
    { en: "Spring", tr: "İlkbahar", level: "A1" }, // [cite: 2359]
    { en: "Stand", tr: "Durmak, dikilmek", level: "A1" }, // [cite: 2359]
    { en: "Star", tr: "Yıldız, ünlü", level: "A1" }, // [cite: 2359]
    { en: "Start", tr: "Başlamak", level: "A1" }, // [cite: 2359]
    { en: "Statement", tr: "Söz, ifade, beyan, demeç", level: "A1" }, // [cite: 2359]
    { en: "Station", tr: "İstasyon", level: "A1" }, // [cite: 2359]
    { en: "Stay", tr: "Kalmak", level: "A1" }, // [cite: 2359]
    { en: "Still", tr: "Hala, henüz", level: "A1" }, // [cite: 2359]
    { en: "Stop", tr: "Durmak", level: "A1" }, // [cite: 2359]
    { en: "Story", tr: "Hikaye", level: "A1" }, // [cite: 2359]
    { en: "Street", tr: "Sokak", level: "A1" }, // [cite: 2359]
    { en: "Strong", tr: "Güçlü", level: "A1" }, // [cite: 2359]
    { en: "Student", tr: "Öğrenci", level: "A1" }, // [cite: 2359]
    { en: "Study", tr: "Çalışmak", level: "A1" }, // [cite: 2359]
    { en: "Style", tr: "Stil", level: "A1" }, // [cite: 2359]
    { en: "Subject", tr: "Ders, özne, konu", level: "A1" }, // [cite: 2359]
    { en: "Success", tr: "Başarı", level: "A1" }, // [cite: 2359]
    { en: "Sugar", tr: "Şeker", level: "A1" }, // [cite: 2359]
    { en: "Summer", tr: "Yaz", level: "A1" }, // [cite: 2359]
    { en: "Sun", tr: "Güneş", level: "A1" }, // [cite: 2360]
    { en: "Supermarket", tr: "Süpermarket", level: "A1" }, // [cite: 2360]
    { en: "Sure", tr: "Emin, kesin", level: "A1" }, // [cite: 2360]
    { en: "Sweater", tr: "Süveter", level: "A1" }, // [cite: 2360]
    { en: "Swim", tr: "Yüzmek", level: "A1" }, // [cite: 2360]
    { en: "Swimming", tr: "Yüzme", level: "A1" }, // [cite: 2360]
    { en: "Table", tr: "Masa", level: "A1" }, // [cite: 2360]
    { en: "Take", tr: "Almak", level: "A1" }, // [cite: 2360]
    { en: "Talk", tr: "Konuşmak", level: "A1" }, // [cite: 2360]
    { en: "Tall", tr: "Uzun", level: "A1" }, // [cite: 2360]
    { en: "Taxi", tr: "Taksi", level: "A1" }, // [cite: 2360]
    { en: "Tea", tr: "Çay", level: "A1" }, // [cite: 2360]
    { en: "Teach", tr: "Öğretmek", level: "A1" }, // [cite: 2360]
    { en: "Teacher", tr: "Öğretmen", level: "A1" }, // [cite: 2360]
    { en: "Team", tr: "Tim, takım", level: "A1" }, // [cite: 2360]
    { en: "Teenager", tr: "Ergen, yeniyetme", level: "A1" }, // [cite: 2360]
    { en: "Telephone", tr: "Telefon", level: "A1" }, // [cite: 2360]
    { en: "Television", tr: "Televizyon", level: "A1" }, // [cite: 2360]
    { en: "Tell", tr: "Söylemek, demek", level: "A1" }, // [cite: 2360]
    { en: "Tennis", tr: "Tenis", level: "A1" }, // [cite: 2361]
    { en: "Terrible", tr: "Korkunç", level: "A1" }, // [cite: 2361]
    { en: "Test", tr: "Test, sınav yapmak", level: "A1" }, // [cite: 2361]
    { en: "Text", tr: "Metin", level: "A1" }, // [cite: 2361]
    { en: "Thank", tr: "Teşekkür etmek", level: "A1" }, // [cite: 2361]
    { en: "Thanks", tr: "Teşekkür ederim", level: "A1" }, // [cite: 2361]
    { en: "Thing", tr: "Şey", level: "A1" }, // [cite: 2361]
    { en: "Think", tr: "Düşünmek", level: "A1" }, // [cite: 2361]
    { en: "Thirsty", tr: "Susamış", level: "A1" }, // [cite: 2361]
    { en: "Ticket", tr: "Bilet", level: "A1" }, // [cite: 2362]
    { en: "Time", tr: "Zaman", level: "A1" }, // [cite: 2362]
    { en: "Tired", tr: "Yorulmuş, yorgun", level: "A1" }, // [cite: 2362]
    { en: "Title", tr: "Başlık", level: "A1" }, // [cite: 2362]
    { en: "Today", tr: "Bugün", level: "A1" }, // [cite: 2362]
    { en: "Together", tr: "Birlikte", level: "A1" }, // [cite: 2362]
    { en: "Toilet", tr: "Tuvalet", level: "A1" }, // [cite: 2362]
    { en: "Tomato", tr: "Domates", level: "A1" }, // [cite: 2362]
    { en: "Tomorrow", tr: "Yarın", level: "A1" }, // [cite: 2362]
    { en: "Tonight", tr: "Bu gece", level: "A1" }, // [cite: 2362]
    { en: "Tooth", tr: "Diş", level: "A1" }, // [cite: 2362]
    { en: "Topic", tr: "Konu", level: "A1" }, // [cite: 2362]
    { en: "Tourist", tr: "Turist", level: "A1" }, // [cite: 2362]
    { en: "Town", tr: "Şehir", level: "A1" }, // [cite: 2362]
    { en: "Traffic", tr: "Trafik", level: "A1" }, // [cite: 2362]
    { en: "Train", tr: "Tren", level: "A1" }, // [cite: 2362]
    { en: "Travel", tr: "Seyahat, seyahat etmek", level: "A1" }, // [cite: 2363]
    { en: "Tree", tr: "Ağaç", level: "A1" }, // [cite: 2363]
    { en: "Trousers", tr: "Pantolon", level: "A1" }, // [cite: 2363]
    { en: "True", tr: "Doğru", level: "A1" }, // [cite: 2363]
    { en: "Try", tr: "Denemek", level: "A1" }, // [cite: 2363]
    { en: "Turn", tr: "Sıra, dönmek, döndürmek", level: "A1" }, // [cite: 2363]
    { en: "TV", tr: "TV", level: "A1" }, // [cite: 2363]
    { en: "Type", tr: "Tür, tip, cins", level: "A1" }, // [cite: 2363]
    { en: "Umbrella", tr: "Şemsiye", level: "A1" }, // [cite: 2363]
    { en: "Uncle", tr: "Amca", level: "A1" }, // [cite: 2363]
    { en: "Under", tr: "Altında", level: "A1" }, // [cite: 2363]
    { en: "Understand", tr: "Anlamak", level: "A1" }, // [cite: 2363]
    { en: "University", tr: "Üniversite", level: "A1" }, // [cite: 2363]
    { en: "Up", tr: "Yukarı", level: "A1" }, // [cite: 2363]
    { en: "Upstairs", tr: "Üst katta olan", level: "A1" }, // [cite: 2364]
    { en: "Use", tr: "Kullanmak", level: "A1" }, // [cite: 2364]
    { en: "Useful", tr: "Kullanışlı", level: "A1" }, // [cite: 2364]
    { en: "Usually", tr: "Genellikle", level: "A1" }, // [cite: 2364]
    { en: "Vacation", tr: "Tatil", level: "A1" }, // [cite: 2364]
    { en: "Vegetable", tr: "Sebze", level: "A1" }, // [cite: 2364]
    { en: "Very", tr: "Çok", level: "A1" }, // [cite: 2364]
    { en: "Video", tr: "Video", level: "A1" }, // [cite: 2364]
    { en: "Village", tr: "Köy", level: "A1" }, // [cite: 2364]
    { en: "Visit", tr: "Ziyaret, ziyaret etmek", level: "A1" }, // [cite: 2364]
    { en: "Visitor", tr: "Ziyaretçi", level: "A1" }, // [cite: 2364]
    { en: "Wait", tr: "Beklemek", level: "A1" }, // [cite: 2364]
    { en: "Waiter", tr: "Garson", level: "A1" }, // [cite: 2364]
    { en: "Wake", tr: "Uyanmak", level: "A1" }, // [cite: 2364]
    { en: "Walk", tr: "Yürümek", level: "A1" }, // [cite: 2364]
    { en: "Wall", tr: "Duvar", level: "A1" }, // [cite: 2364]
    { en: "Want", tr: "İstemek", level: "A1" }, // [cite: 2364]
    { en: "Warm", tr: "Sıcak", level: "A1" }, // [cite: 2364]
    { en: "Wash", tr: "Yıkamak", level: "A1" }, // [cite: 2364]
    { en: "Watch", tr: "İzlemek, kol saati", level: "A1" }, // [cite: 2365]
    { en: "Water", tr: "Su", level: "A1" }, // [cite: 2365]
    { en: "Way", tr: "Yol, yöntem, tarz", level: "A1" }, // [cite: 2365]
    { en: "Wear", tr: "Giymek", level: "A1" }, // [cite: 2365]
    { en: "Weather", tr: "Hava durumu", level: "A1" }, // [cite: 2365]
    { en: "Website", tr: "Website", level: "A1" }, // [cite: 2365]
    { en: "Week", tr: "Hafta", level: "A1" }, // [cite: 2365]
    { en: "Weekend", tr: "Hafta sonu", level: "A1" }, // [cite: 2365]
    { en: "Welcome", tr: "Hoş geldin", level: "A1" }, // [cite: 2365]
    { en: "Well", tr: "İyi", level: "A1" }, // [cite: 2365]
    { en: "West", tr: "Batı", level: "A1" }, // [cite: 2365]
    { en: "White", tr: "Beyaz", level: "A1" }, // [cite: 2365]
    { en: "Wife", tr: "Karı", level: "A1" }, // [cite: 2365]
    { en: "Win", tr: "Kazanmak", level: "A1" }, // [cite: 2365]
    { en: "Window", tr: "Pencere", level: "A1" }, // [cite: 2366]
    { en: "Wine", tr: "Şarap", level: "A1" }, // [cite: 2366]
    { en: "Winter", tr: "Kış", level: "A1" }, // [cite: 2366]
    { en: "Woman", tr: "Kadın", level: "A1" }, // [cite: 2366]
    { en: "Wonderful", tr: "Harika", level: "A1" }, // [cite: 2366]
    { en: "Word", tr: "Kelime", level: "A1" }, // [cite: 2366]
    { en: "Work", tr: "İş, çalışmak", level: "A1" }, // [cite: 2366]
    { en: "Worker", tr: "İşçi", level: "A1" }, // [cite: 2366]
    { en: "World", tr: "Dünya", level: "A1" }, // [cite: 2366]
    { en: "Write", tr: "Yazmak", level: "A1" }, // [cite: 2366]
    { en: "Writer", tr: "Yazar", level: "A1" }, // [cite: 2366]
    { en: "Writing", tr: "Yazı", level: "A1" }, // [cite: 2366]
    { en: "Wrong", tr: "Yanlış", level: "A1" }, // [cite: 2366]
    { en: "Yeah", tr: "He, tamam, evet", level: "A1" }, // [cite: 2366]
    { en: "Year", tr: "Yıl", level: "A1" }, // [cite: 2366]
    { en: "Yellow", tr: "Sarı", level: "A1" }, // [cite: 2366]
    { en: "Yes", tr: "Evet", level: "A1" }, // [cite: 2366]
    { en: "Yesterday", tr: "Dün", level: "A1" }, // [cite: 2366]
    { en: "Young", tr: "Genç", level: "A1" }, // [cite: 2367]
    { en: "Yourself", tr: "Kendin, kendiniz", level: "A1" }, // [cite: 2367]

    // --- A2 SEVİYE KELİMELER ---
    { en: "Ability", tr: "Yetenek", level: "A2" }, // [cite: 2375]
    { en: "Able", tr: "Gücü yeten, yapabilen", level: "A2" }, // [cite: 2375]
    { en: "Abroad", tr: "Yurt dışında", level: "A2" }, // [cite: 2375]
    { en: "Accept", tr: "Kabul etmek", level: "A2" }, // [cite: 2375]
    { en: "Accident", tr: "Kaza, rastlantı", level: "A2" }, // [cite: 2375]
    { en: "According to", tr: "-e göre", level: "A2" }, // [cite: 2376]
    { en: "Achieve", tr: "Başarmak", level: "A2" }, // [cite: 2376]
    { en: "Act", tr: "Yapmak", level: "A2" }, // [cite: 2376]
    { en: "Active", tr: "Aktif", level: "A2" }, // [cite: 2376]
    { en: "Actually", tr: "Fiilen, aslında, hakikaten, gerçekten", level: "A2" }, // [cite: 2376]
    { en: "Advantage", tr: "Avantaj", level: "A2" }, // [cite: 2376]
    { en: "Adventure", tr: "Macera", level: "A2" }, // [cite: 2376]
    { en: "Advertise", tr: "Reklamını yapmak, tanıtım yapmak", level: "A2" }, // [cite: 2376]
    { en: "Advertisement", tr: "Reklam", level: "A2" }, // [cite: 2376]
    { en: "Affect", tr: "Tesir etmek, etkilemek", level: "A2" }, // [cite: 2376]
    { en: "Against", tr: "-e karşı", level: "A2" }, // [cite: 2376]
    { en: "Airline", tr: "Hava yolu", level: "A2" }, // [cite: 2376]
    { en: "Alive", tr: "Canlı", level: "A2" }, // [cite: 2376]
    { en: "All right", tr: "Elbette ki, okey, tamam", level: "A2" }, // [cite: 2376]
    { en: "Allow", tr: "İzin vermek", level: "A2" }, // [cite: 2376]
    { en: "Almost", tr: "Neredeyse", level: "A2" }, // [cite: 2376]
    { en: "Alone", tr: "Yalnız", level: "A2" }, // [cite: 2376]
    { en: "Along", tr: "Boyunca", level: "A2" }, // [cite: 2376]
    { en: "Already", tr: "Hazır", level: "A2" }, // [cite: 2376]
    { en: "Alternative", tr: "Alternatif", level: "A2" }, // [cite: 2376]
    { en: "Although", tr: "-e rağmen", level: "A2" }, // [cite: 2376]
    { en: "Among", tr: "Arasında", level: "A2" }, // [cite: 2377]
    { en: "Amount", tr: "Miktar, tutar", level: "A2" }, // [cite: 2377]
    { en: "Ancient", tr: "Kadim", level: "A2" }, // [cite: 2377]
    { en: "Ankle", tr: "Ayak bileği", level: "A2" }, // [cite: 2377]
    { en: "Anybody", tr: "Hiçkimse", level: "A2" }, // [cite: 2377]
    { en: "Any more", tr: "Artık, başka", level: "A2" }, // [cite: 2377]
    { en: "Anyway", tr: "Neyse, her neyse", level: "A2" }, // [cite: 2377]
    { en: "Anywhere", tr: "Herhangi bir yer, hiçbir yer", level: "A2" }, // [cite: 2377]
    { en: "App", tr: "Uygulama", level: "A2" }, // [cite: 2377]
    { en: "Appear", tr: "Görünmek, ortaya çıkmak", level: "A2" }, // [cite: 2377]
    { en: "Appearance", tr: "Görünüş, ortaya çıkış", level: "A2" }, // [cite: 2377]
    { en: "Apply", tr: "Uygulamak", level: "A2" }, // [cite: 2377]
    { en: "Architect", tr: "Mimar", level: "A2" }, // [cite: 2377]
    { en: "Architecture", tr: "Mimarlık, inşaat", level: "A2" }, // [cite: 2377]
    { en: "Argue", tr: "Tartışmak", level: "A2" }, // [cite: 2377]
    { en: "Argument", tr: "Argüman", level: "A2" }, // [cite: 2377]
    { en: "Army", tr: "Ordu", level: "A2" }, // [cite: 2377]
    { en: "Arrange", tr: "Düzenlemek, ayarlamak", level: "A2" }, // [cite: 2377]
    { en: "Arrangement", tr: "Aranjman, düzenleme, ayarlama", level: "A2" }, // [cite: 2377]
    { en: "Asleep", tr: "Uyuyan, tembel, uyuşuk", level: "A2" }, // [cite: 2377]
    { en: "Assistant", tr: "Asistan", level: "A2" }, // [cite: 2377]
    { en: "Athlete", tr: "Atlet", level: "A2" }, // [cite: 2378]
    { en: "Attack", tr: "Saldırı, saldırmak", level: "A2" }, // [cite: 2378]
    { en: "Attend", tr: "Katılmak", level: "A2" }, // [cite: 2378]
    { en: "Attention", tr: "Dikkat", level: "A2" }, // [cite: 2378]
    { en: "Attractive", tr: "Çekici", level: "A2" }, // [cite: 2378]
    { en: "Audience", tr: "Seyirci", level: "A2" }, // [cite: 2378]
    { en: "Author", tr: "Yazar", level: "A2" }, // [cite: 2378]
    { en: "Available", tr: "Müsait, uygun", level: "A2" }, // [cite: 2378]
    { en: "Average", tr: "Ortalama", level: "A2" }, // [cite: 2378]
    { en: "Avoid", tr: "Kaçınmak", level: "A2" }, // [cite: 2378]
    { en: "Award", tr: "Hediye, ödül", level: "A2" }, // [cite: 2378]
    { en: "Awful", tr: "Berbat", level: "A2" }, // [cite: 2378]
    { en: "Background", tr: "Arka plan", level: "A2" }, // [cite: 2378]
    { en: "Badly", tr: "Berbat bir şekilde", level: "A2" }, // [cite: 2378]
    { en: "Baseball", tr: "Beyzbol", level: "A2" }, // [cite: 2378]
    { en: "Based", tr: "Esaslı, yerleşik", level: "A2" }, // [cite: 2378]
    { en: "Basketball", tr: "Basketbol", level: "A2" }, // [cite: 2378]
    { en: "Bean", tr: "Fasulye", level: "A2" }, // [cite: 2378]
    { en: "Bear", tr: "Ayı", level: "A2" }, // [cite: 2378]
    { en: "Beat", tr: "Dövmek", level: "A2" }, // [cite: 2378]
    { en: "Beef", tr: "Sığır eti", level: "A2" }, // [cite: 2378]
    { en: "Behave", tr: "Davranmak", level: "A2" }, // [cite: 2379]
    { en: "Behaviour", tr: "Davranış", level: "A2" }, // [cite: 2379]
    { en: "Belong", tr: "Ait olmak", level: "A2" }, // [cite: 2379]
    { en: "Belt", tr: "Kayış, kemer", level: "A2" }, // [cite: 2379]
    { en: "Benefit", tr: "Fayda", level: "A2" }, // [cite: 2379]
    { en: "Best", tr: "En iyisi", level: "A2" }, // [cite: 2379]
    { en: "Better", tr: "Daha iyi", level: "A2" }, // [cite: 2379]
    { en: "Between", tr: "Arasında", level: "A2" }, // [cite: 2379]
    { en: "Billion", tr: "Milyar", level: "A2" }, // [cite: 2379]
    { en: "Biology", tr: "Biyoloji", level: "A2" }, // [cite: 2379]
    { en: "Birth", tr: "Doğum", level: "A2" }, // [cite: 2379]
    { en: "Biscuit", tr: "Bisküvi", level: "A2" }, // [cite: 2379]
    { en: "Blank", tr: "Boşluk, boş", level: "A2" }, // [cite: 2379]
    { en: "Blood", tr: "Kan", level: "A2" }, // [cite: 2379]
    { en: "Blow", tr: "Esmek", level: "A2" }, // [cite: 2379]
    { en: "Board", tr: "Tahta", level: "A2" }, // [cite: 2379]
    { en: "Boil", tr: "Kaynamak", level: "A2" }, // [cite: 2379]
    { en: "Bone", tr: "Kılçık, kemik", level: "A2" }, // [cite: 2379]
    { en: "Book", tr: "Ayırtmak", level: "A2" }, // [cite: 2379]
    { en: "Borrow", tr: "Ödünç almak", level: "A2" }, // [cite: 2379]
    { en: "Boss", tr: "Patron", level: "A2" }, // [cite: 2379]
    { en: "Bottom", tr: "Dip, en alt", level: "A2" }, // [cite: 2379]
    { en: "Bowl", tr: "Tas", level: "A2" }, // [cite: 2379]
    { en: "Brain", tr: "Beyin", level: "A2" }, // [cite: 2380]
    { en: "Bridge", tr: "Köprü", level: "A2" }, // [cite: 2380]
    { en: "Bright", tr: "Parlak", level: "A2" }, // [cite: 2380]
    { en: "Brilliant", tr: "Harika", level: "A2" }, // [cite: 2380]
    { en: "Broken", tr: "Arızalı, kırılmış", level: "A2" }, // [cite: 2380]
    { en: "Brush", tr: "Fırçalamak", level: "A2" }, // [cite: 2380]
    { en: "Burn", tr: "Yakmak", level: "A2" }, // [cite: 2380]
    { en: "Businessman", tr: "İş adamı", level: "A2" }, // [cite: 2380]
    { en: "Button", tr: "Düğme", level: "A2" }, // [cite: 2380]
    { en: "Camp", tr: "Kamp", level: "A2" }, // [cite: 2380]
    { en: "Camping", tr: "Kamp yapma", level: "A2" }, // [cite: 2380]
    { en: "Can", tr: "Teneke kutu", level: "A2" }, // [cite: 2380]
    { en: "Care", tr: "İlgi, ilgilenmek", level: "A2" }, // [cite: 2380]
    { en: "Careful", tr: "Dikkatli", level: "A2" }, // [cite: 2380]
    { en: "Carefully", tr: "Dikkatlice", level: "A2" }, // [cite: 2380]
    { en: "Carpet", tr: "Halı", level: "A2" }, // [cite: 2380]
    { en: "Cartoon", tr: "Çizgi film", level: "A2" }, // [cite: 2380]
    { en: "Case", tr: "Dava", level: "A2" }, // [cite: 2380]
    { en: "Cash", tr: "Nakit", level: "A2" }, // [cite: 2380]
    { en: "Castle", tr: "Kale", level: "A2" }, // [cite: 2380]
    { en: "Catch", tr: "Yakalamak", level: "A2" }, // [cite: 2380]
    { en: "Cause", tr: "Sebep, sebep olmak", level: "A2" }, // [cite: 2380]
    { en: "Celebrate", tr: "Kutlamak", level: "A2" }, // [cite: 2380]
    { en: "Celebrity", tr: "Kutlama", level: "A2" }, // [cite: 2381]
    { en: "Certain", tr: "Kesin, belirli", level: "A2" }, // [cite: 2381]
    { en: "Certainly", tr: "Muhakkak, kesinlikle", level: "A2" }, // [cite: 2381]
    { en: "Chance", tr: "Şans", level: "A2" }, // [cite: 2381]
    { en: "Character", tr: "Karakter", level: "A2" }, // [cite: 2381]
    { en: "Charity", tr: "Bağış, hayırseverlik", level: "A2" }, // [cite: 2381]
    { en: "Chat", tr: "Konuşma, sohbet etmek", level: "A2" }, // [cite: 2381]
    { en: "Check", tr: "Kontrol", level: "A2" }, // [cite: 2381]
    { en: "Chef", tr: "Aşçı", level: "A2" }, // [cite: 2381]
    { en: "Chemistry", tr: "Kimya", level: "A2" }, // [cite: 2381]
    { en: "Choice", tr: "Tercih, seçenek", level: "A2" }, // [cite: 2381]
    { en: "Church", tr: "Kilise", level: "A2" }, // [cite: 2381]
    { en: "Cigarette", tr: "Sigara", level: "A2" }, // [cite: 2381]
    { en: "Circle", tr: "Halka, daire, muhit", level: "A2" }, // [cite: 2381]
    { en: "Classical", tr: "Klasik", level: "A2" }, // [cite: 2381]
    { en: "Clear", tr: "Temiz", level: "A2" }, // [cite: 2381]
    { en: "Clearly", tr: "Açık bir şekilde", level: "A2" }, // [cite: 2381]
    { en: "Clever", tr: "Akıllı, zeki", level: "A2" }, // [cite: 2381]
    { en: "Climate", tr: "İklim", level: "A2" }, // [cite: 2381]
    { en: "Close", tr: "Yakın", level: "A2" }, // [cite: 2381]
    { en: "Closed", tr: "Kapalı", level: "A2" }, // [cite: 2381]
    { en: "Clothing", tr: "Giysi, giyim", level: "A2" }, // [cite: 2381]
    { en: "Cloud", tr: "Bulut", level: "A2" }, // [cite: 2381]
    { en: "Coach", tr: "Antrenör", level: "A2" }, // [cite: 2382]
    { en: "Coast", tr: "Sahil", level: "A2" }, // [cite: 2382]
    { en: "Code", tr: "Kod", level: "A2" }, // [cite: 2382]
    { en: "Colleague", tr: "Kolej", level: "A2" }, // [cite: 2382]
    { en: "Collect", tr: "Toplamak", level: "A2" }, // [cite: 2382]
    { en: "Column", tr: "Köşe", level: "A2" }, // [cite: 2382]
    { en: "Comedy", tr: "Komedi", level: "A2" }, // [cite: 2382]
    { en: "Comfortable", tr: "Konforlu", level: "A2" }, // [cite: 2382]
    { en: "Comment", tr: "Yorum", level: "A2" }, // [cite: 2382]
    { en: "Communicate", tr: "İletişim kurmak", level: "A2" }, // [cite: 2382]
    { en: "Community", tr: "Toplum", level: "A2" }, // [cite: 2382]
    { en: "Compete", tr: "Rekabet etmek, yarışmak", level: "A2" }, // [cite: 2382]
    { en: "Competition", tr: "Yarışma", level: "A2" }, // [cite: 2382]
    { en: "Complain", tr: "Şikayet etmek", level: "A2" }, // [cite: 2382]
    { en: "Completely", tr: "Tamamen", level: "A2" }, // [cite: 2382]
    { en: "Condition", tr: "Durum, şart", level: "A2" }, // [cite: 2382]
    { en: "Conference", tr: "Konferans", level: "A2" }, // [cite: 2382]
    { en: "Connect", tr: "Bağlamak", level: "A2" }, // [cite: 2382]
    { en: "Connected", tr: "Bağlı", level: "A2" }, // [cite: 2382]
    { en: "Consider", tr: "Düşünmek", level: "A2" }, // [cite: 2382]
    { en: "Contain", tr: "İçermek", level: "A2" }, // [cite: 2382]
    { en: "Context", tr: "Bağlam", level: "A2" }, // [cite: 2382]
    { en: "Continent", tr: "Kıta", level: "A2" }, // [cite: 2382]
    { en: "Continue", tr: "Devam etmek", level: "A2" }, // [cite: 2383]
    { en: "Control", tr: "Kontrol, kontrol etmek", level: "A2" }, // [cite: 2383]
    { en: "Conversation", tr: "Konuşma, sohbet", level: "A2" }, // [cite: 2383]
    { en: "Cook", tr: "Aşçı", level: "A2" }, // [cite: 2383]
    { en: "Cooker", tr: "Ocak, fırın", level: "A2" }, // [cite: 2383]
    { en: "Copy", tr: "Kopyalamak", level: "A2" }, // [cite: 2383]
    { en: "Corner", tr: "Köşe", level: "A2" }, // [cite: 2383]
    { en: "Correctly", tr: "Düzgün bir şekilde", level: "A2" }, // [cite: 2383]
    { en: "Count", tr: "Saymak", level: "A2" }, // [cite: 2383]
    { en: "Couple", tr: "Çift", level: "A2" }, // [cite: 2383]
    { en: "Cover", tr: "Kapamak, örtmek", level: "A2" }, // [cite: 2383]
    { en: "Crazy", tr: "Çılgın", level: "A2" }, // [cite: 2383]
    { en: "Creative", tr: "Yaratıcı", level: "A2" }, // [cite: 2383]
    { en: "Credit", tr: "Kredi", level: "A2" }, // [cite: 2383]
    { en: "Crime", tr: "Suç", level: "A2" }, // [cite: 2383]
    { en: "Criminal", tr: "Suçlu, sabıkalı", level: "A2" }, // [cite: 2383]
    { en: "Cross", tr: "Geçmek", level: "A2" }, // [cite: 2383]
    { en: "Crowd", tr: "Kalabalık, izdiham", level: "A2" }, // [cite: 2383]
    { en: "Crowded", tr: "Kalabalık", level: "A2" }, // [cite: 2383]
    { en: "Cry", tr: "Ağlamak", level: "A2" }, // [cite: 2383]
    { en: "Cupboard", tr: "Dolap, büfe", level: "A2" }, // [cite: 2383]
    { en: "Curly", tr: "Kıvırcık", level: "A2" }, // [cite: 2383]
    { en: "Cycle", tr: "Devir", level: "A2" }, // [cite: 2383]
    { en: "Daily", tr: "Günlük", level: "A2" }, // [cite: 2384]
    { en: "Danger", tr: "Tehlike", level: "A2" }, // [cite: 2384]
    { en: "Dark", tr: "Karanlık", level: "A2" }, // [cite: 2384]
    { en: "Data", tr: "Data, veri", level: "A2" }, // [cite: 2384]
    { en: "Dead", tr: "Ölü", level: "A2" }, // [cite: 2384]
    { en: "Deal", tr: "Anlaşma", level: "A2" }, // [cite: 2384]
    { en: "Dear", tr: "Tatlı, sevgili", level: "A2" }, // [cite: 2384]
    { en: "Death", tr: "Ölüm", level: "A2" }, // [cite: 2384]
    { en: "Decision", tr: "Karar", level: "A2" }, // [cite: 2384]
    { en: "Deep", tr: "Derin", level: "A2" }, // [cite: 2384]
    { en: "Definitely", tr: "Kesinlikle", level: "A2" }, // [cite: 2384]
    { en: "Degree", tr: "Sınıf, puan", level: "A2" }, // [cite: 2384]
    { en: "Dentist", tr: "Dişçi", level: "A2" }, // [cite: 2384]
    { en: "Department", tr: "Bölüm", level: "A2" }, // [cite: 2384]
    { en: "Depend", tr: "Dayanmak", level: "A2" }, // [cite: 2384]
    { en: "Desert", tr: "Tatlı, çöl", level: "A2" }, // [cite: 2384]
    { en: "Designer", tr: "Tasarımcı", level: "A2" }, // [cite: 2384]
    { en: "Destroy", tr: "Yıkmak", level: "A2" }, // [cite: 2384]
    { en: "Detective", tr: "Dedektif", level: "A2" }, // [cite: 2384]
    { en: "Develop", tr: "Geliştirmek", level: "A2" }, // [cite: 2384]
    { en: "Device", tr: "Alet, edevat", level: "A2" }, // [cite: 2384]
    { en: "Diary", tr: "Günlük", level: "A2" }, // [cite: 2384]
    { en: "Differently", tr: "Farklı bir şekilde", level: "A2" }, // [cite: 2384]
    { en: "Digital", tr: "Dijital", level: "A2" }, // [cite: 2385]
    { en: "Direct", tr: "Doğru, direkt", level: "A2" }, // [cite: 2385]
    { en: "Direction", tr: "Yön", level: "A2" }, // [cite: 2385]
    { en: "Director", tr: "Yönetmen", level: "A2" }, // [cite: 2385]
    { en: "Disagree", tr: "Katılmamak", level: "A2" }, // [cite: 2385]
    { en: "Disappear", tr: "Ortadan kaybolmak", level: "A2" }, // [cite: 2385]
    { en: "Disaster", tr: "Felaket", level: "A2" }, // [cite: 2385]
    { en: "Discover", tr: "Keşfetmek", level: "A2" }, // [cite: 2385]
    { en: "Discovery", tr: "Keşif", level: "A2" }, // [cite: 2385]
    { en: "Discussion", tr: "Tartışma", level: "A2" }, // [cite: 2385]
    { en: "Disease", tr: "Hastalık", level: "A2" }, // [cite: 2385]
    { en: "Distance", tr: "Mesafe", level: "A2" }, // [cite: 2385]
    { en: "Divorced", tr: "Boşanmış", level: "A2" }, // [cite: 2385]
    { en: "Document", tr: "Belge", level: "A2" }, // [cite: 2385]
    { en: "Double", tr: "Çift", level: "A2" }, // [cite: 2385]
    { en: "Download", tr: "İndirmek", level: "A2" }, // [cite: 2385]
    { en: "Downstairs", tr: "Altkat", level: "A2" }, // [cite: 2385]
    { en: "Drama", tr: "Drama", level: "A2" }, // [cite: 2385]
    { en: "Drawing", tr: "Çizme", level: "A2" }, // [cite: 2385]
    { en: "Dream", tr: "Hayal kurma", level: "A2" }, // [cite: 2385]
    { en: "Drive", tr: "Dürtü", level: "A2" }, // [cite: 2385]
    { en: "Driving", tr: "Sürüş", level: "A2" }, // [cite: 2385]
    { en: "Drop", tr: "Düşürmek", level: "A2" }, // [cite: 2385]
    { en: "Drug", tr: "Uyuşturucu", level: "A2" }, // [cite: 2386]
    { en: "Dry", tr: "Kuru, kurulamak", level: "A2" }, // [cite: 2386]
    { en: "Earn", tr: "Para kazanmak", level: "A2" }, // [cite: 2386]
    { en: "Earth", tr: "Kara, yeryüzü, dünya", level: "A2" }, // [cite: 2386]
    { en: "Easily", tr: "Kolayca", level: "A2" }, // [cite: 2386]
    { en: "Education", tr: "Eğitim", level: "A2" }, // [cite: 2386]
    { en: "Effect", tr: "Etki", level: "A2" }, // [cite: 2386]
    { en: "Either", tr: "İki, her iki, herhangi biri", level: "A2" }, // [cite: 2386]
    { en: "Electronic", tr: "Elektronik", level: "A2" }, // [cite: 2386]
    { en: "Employ", tr: "İşe almak", level: "A2" }, // [cite: 2386]
    { en: "Employee", tr: "İşçi", level: "A2" }, // [cite: 2386]
    { en: "Employer", tr: "İşveren", level: "A2" }, // [cite: 2386]
    { en: "Empty", tr: "Boş", level: "A2" }, // [cite: 2386]
    { en: "Ending", tr: "Son", level: "A2" }, // [cite: 2386]
    { en: "Energy", tr: "Enerji", level: "A2" }, // [cite: 2386]
    { en: "Engine", tr: "Motor", level: "A2" }, // [cite: 2386]
    { en: "Engineer", tr: "Mühendis", level: "A2" }, // [cite: 2386]
    { en: "Enormous", tr: "Devasa", level: "A2" }, // [cite: 2386]
    { en: "Enter", tr: "Girmek", level: "A2" }, // [cite: 2386]
    { en: "Environment", tr: "Çevre", level: "A2" }, // [cite: 2386]
    { en: "Equipment", tr: "Ekipman", level: "A2" }, // [cite: 2386]
    { en: "Error", tr: "Hata", level: "A2" }, // [cite: 2386]
    { en: "Especially", tr: "Özellikle", level: "A2" }, // [cite: 2386]
    { en: "Essay", tr: "Makale", level: "A2" }, // [cite: 2387]
    { en: "Everyday", tr: "Her gün", level: "A2" }, // [cite: 2387]
    { en: "Everywhere", tr: "Her yer", level: "A2" }, // [cite: 2387]
    { en: "Evidence", tr: "Kanıt", level: "A2" }, // [cite: 2387]
    { en: "Exact", tr: "Kesin, tamı tamına", level: "A2" }, // [cite: 2387]
    { en: "Exactly", tr: "Kesinlikle", level: "A2" }, // [cite: 2387]
    { en: "Excellent", tr: "Harika", level: "A2" }, // [cite: 2387]
    { en: "Except", tr: "Dışında", level: "A2" }, // [cite: 2387]
    { en: "Exist", tr: "Var olmak", level: "A2" }, // [cite: 2387]
    { en: "Expect", tr: "Ummak", level: "A2" }, // [cite: 2387]
    { en: "Experience", tr: "Deneyim", level: "A2" }, // [cite: 2387]
    { en: "Experiment", tr: "Tecrübe", level: "A2" }, // [cite: 2387]
    { en: "Expert", tr: "Uzman", level: "A2" }, // [cite: 2387]
    { en: "Explanation", tr: "Açıklama", level: "A2" }, // [cite: 2387]
    { en: "Express", tr: "İfade etmek", level: "A2" }, // [cite: 2387]
    { en: "Expression", tr: "İfade", level: "A2" }, // [cite: 2387]
    { en: "Extreme", tr: "Aşırı", level: "A2" }, // [cite: 2387]
    { en: "Extremely", tr: "Aşırı boyutta", level: "A2" }, // [cite: 2387]
    { en: "Factor", tr: "Etken, faktör", level: "A2" }, // [cite: 2387]
    { en: "Factory", tr: "Fabrika", level: "A2" }, // [cite: 2387]
    { en: "Fail", tr: "Başarısız olmak", level: "A2" }, // [cite: 2387]
    { en: "Fair", tr: "Adil", level: "A2" }, // [cite: 2387]
    { en: "Fall", tr: "Sonbahar, düşüş", level: "A2" }, // [cite: 2387]
    { en: "Fan", tr: "Pervane, taraftar", level: "A2" }, // [cite: 2388]
    { en: "Farm", tr: "Çiftçilik yapmak, ekip biçmek", level: "A2" }, // [cite: 2388]
    { en: "Farming", tr: "Tarım", level: "A2" }, // [cite: 2388]
    { en: "Fashion", tr: "Moda", level: "A2" }, // [cite: 2388]
    { en: "Fat", tr: "Yağ", level: "A2" }, // [cite: 2388]
    { en: "Fear", tr: "Korku", level: "A2" }, // [cite: 2388]
    { en: "Feature", tr: "Özellik", level: "A2" }, // [cite: 2388]
    { en: "Feed", tr: "Beslemek", level: "A2" }, // [cite: 2388]
    { en: "Female", tr: "Kadın", level: "A2" }, // [cite: 2388]
    { en: "Fiction", tr: "Kurgu", level: "A2" }, // [cite: 2388]
    { en: "Field", tr: "Alan, saha", level: "A2" }, // [cite: 2388]
    { en: "Fight", tr: "Dövüşmek", level: "A2" }, // [cite: 2388]
    { en: "Figure", tr: "Figür", level: "A2" }, // [cite: 2388]
    { en: "Film", tr: "Film çekmek", level: "A2" }, // [cite: 2388]
    { en: "Final", tr: "Son, final", level: "A2" }, // [cite: 2388]
    { en: "Finally", tr: "Sonunda", level: "A2" }, // [cite: 2388]
    { en: "Finger", tr: "Parmak", level: "A2" }, // [cite: 2388]
    { en: "Finish", tr: "Nihayet", level: "A2" }, // [cite: 2388]
    { en: "First", tr: "Birinci", level: "A2" }, // [cite: 2388]
    { en: "Firstly", tr: "Öncelikle", level: "A2" }, // [cite: 2388]
    { en: "Fish", tr: "Balık avlamak", level: "A2" }, // [cite: 2388]
    { en: "Fishing", tr: "Balık tutma", level: "A2" }, // [cite: 2388]
    { en: "Fit", tr: "Uymak, uygun", level: "A2" }, // [cite: 2388]
    { en: "Fix", tr: "Düzeltmek", level: "A2" }, // [cite: 2389]
    { en: "Flat", tr: "Apartman", level: "A2" }, // [cite: 2389]
    { en: "Flu", tr: "Grip", level: "A2" }, // [cite: 2389]
    { en: "Fly", tr: "Sinek", level: "A2" }, // [cite: 2389]
    { en: "Flying", tr: "Uçuş", level: "A2" }, // [cite: 2389]
    { en: "Focus", tr: "Odaklanmak", level: "A2" }, // [cite: 2389]
    { en: "Following", tr: "Taraftarlar, izleyen, takip eden", level: "A2" }, // [cite: 2389]
    { en: "Foreign", tr: "Yabancı", level: "A2" }, // [cite: 2389]
    { en: "Forest", tr: "Orman", level: "A2" }, // [cite: 2389]
    { en: "Fork", tr: "Çatal", level: "A2" }, // [cite: 2389]
    { en: "Formal", tr: "Resmi", level: "A2" }, // [cite: 2389]
    { en: "Fortunately", tr: "Şükür ki, neyse ki", level: "A2" }, // [cite: 2389]
    { en: "Forward", tr: "İleri", level: "A2" }, // [cite: 2389]
    { en: "Free", tr: "Beleş, muaf", level: "A2" }, // [cite: 2389]
    { en: "Fresh", tr: "Taze", level: "A2" }, // [cite: 2389]
    { en: "Fridge", tr: "Buzdolabı", level: "A2" }, // [cite: 2389]
    { en: "Frog", tr: "Kurbağa", level: "A2" }, // [cite: 2389]
    { en: "Fun", tr: "Eğlenceli", level: "A2" }, // [cite: 2389]
    { en: "Furniture", tr: "Mobilya", level: "A2" }, // [cite: 2389]
    { en: "Further", tr: "Daha ileri", level: "A2" }, // [cite: 2389]
    { en: "Future", tr: "Müstakbel", level: "A2" }, // [cite: 2389]
    { en: "Gallery", tr: "Galeri", level: "A2" }, // [cite: 2389]
    { en: "Gap", tr: "Boşluk", level: "A2" }, // [cite: 2389]
    { en: "Gas", tr: "Gaz", level: "A2" }, // [cite: 2390]
    { en: "Gate", tr: "Kapı", level: "A2" }, // [cite: 2390]
    { en: "General", tr: "Genel, avam", level: "A2" }, // [cite: 2390]
    { en: "Gift", tr: "Hediye", level: "A2" }, // [cite: 2390]
    { en: "Goal", tr: "Hedef, amaç", level: "A2" }, // [cite: 2390]
    { en: "God", tr: "Tanrı", level: "A2" }, // [cite: 2390]
    { en: "Gold", tr: "Altın", level: "A2" }, // [cite: 2390]
    { en: "Golf", tr: "Golf", level: "A2" }, // [cite: 2390]
    { en: "Good", tr: "İyilik, hayır, hasenat", level: "A2" }, // [cite: 2390]
    { en: "Government", tr: "Hükümet", level: "A2" }, // [cite: 2390]
    { en: "Grass", tr: "Çimen", level: "A2" }, // [cite: 2390]
    { en: "Greet", tr: "Selamlaşmak", level: "A2" }, // [cite: 2390]
    { en: "Ground", tr: "Yer, zemin", level: "A2" }, // [cite: 2390]
    { en: "Guest", tr: "Misafir", level: "A2" }, // [cite: 2390]
    { en: "Guide", tr: "Yönlendirmek", level: "A2" }, // [cite: 2390]
    { en: "Gun", tr: "Silah", level: "A2" }, // [cite: 2390]
    { en: "Guy", tr: "Adam", level: "A2" }, // [cite: 2390]
    { en: "Habit", tr: "Alışkanlık", level: "A2" }, // [cite: 2390]
    { en: "Half", tr: "Yarı yarıya, hemen hemen", level: "A2" }, // [cite: 2390]
    { en: "Hall", tr: "Salon", level: "A2" }, // [cite: 2390]
    { en: "Happily", tr: "Mutlu bir şekilde", level: "A2" }, // [cite: 2390]
    { en: "Headache", tr: "Baş ağrısı", level: "A2" }, // [cite: 2390]
    { en: "Heart", tr: "Kalp", level: "A2" }, // [cite: 2390]
    { en: "Heat", tr: "Sıcaklık, öfke, ısıtmak", level: "A2" }, // [cite: 2391]
    { en: "Heavy", tr: "Ağır", level: "A2" }, // [cite: 2391]
    { en: "Helpful", tr: "Yardımsever", level: "A2" }, // [cite: 2391]
    { en: "Hero", tr: "Kahraman", level: "A2" }, // [cite: 2391]
    { en: "Hide", tr: "Saklanmak", level: "A2" }, // [cite: 2391]
    { en: "High", tr: "Yüksek", level: "A2" }, // [cite: 2391]
    { en: "Hill", tr: "Tepe", level: "A2" }, // [cite: 2391]
    { en: "Hit", tr: "Vurmak, vuruş", level: "A2" }, // [cite: 2391]
    { en: "Hockey", tr: "Hokey", level: "A2" }, // [cite: 2391]
    { en: "Hold", tr: "Tutmak", level: "A2" }, // [cite: 2391]
    { en: "Hole", tr: "Delik", level: "A2" }, // [cite: 2391]
    { en: "Home", tr: "Eve ait", level: "A2" }, // [cite: 2391]
    { en: "Hope", tr: "Umut", level: "A2" }, // [cite: 2391]
    { en: "Huge", tr: "Kocaman", level: "A2" }, // [cite: 2391]
    { en: "Human", tr: "İnsan", level: "A2" }, // [cite: 2391]
    { en: "Hurt", tr: "Yaralamak, acıtmak", level: "A2" }, // [cite: 2391]
    { en: "Ideal", tr: "İdeal", level: "A2" }, // [cite: 2391]
    { en: "Identify", tr: "Tanımlamak", level: "A2" }, // [cite: 2391]
    { en: "Ill", tr: "Hasta", level: "A2" }, // [cite: 2391]
    { en: "Illness", tr: "Hastalık", level: "A2" }, // [cite: 2391]
    { en: "Image", tr: "İmaj", level: "A2" }, // [cite: 2391]
    { en: "Immediately", tr: "Hemen", level: "A2" }, // [cite: 2391]
    { en: "Impossible", tr: "İmkansız", level: "A2" }, // [cite: 2391]
    { en: "Included", tr: "İçeren, içinde", level: "A2" }, // [cite: 2392]
    { en: "Including", tr: "Dahil", level: "A2" }, // [cite: 2392]
    { en: "Increase", tr: "Artmak", level: "A2" }, // [cite: 2392]
    { en: "Incredible", tr: "Harika", level: "A2" }, // [cite: 2392]
    { en: "Independent", tr: "Bağımsız", level: "A2" }, // [cite: 2392]
    { en: "Individual", tr: "Bireysel", level: "A2" }, // [cite: 2392]
    { en: "Industry", tr: "Endüstri", level: "A2" }, // [cite: 2392]
    { en: "Informal", tr: "Resmi olmayan", level: "A2" }, // [cite: 2392]
    { en: "Injury", tr: "Zarar, yara", level: "A2" }, // [cite: 2392]
    { en: "Insect", tr: "Böcek", level: "A2" }, // [cite: 2392]
    { en: "Inside", tr: "İçinde", level: "A2" }, // [cite: 2392]
    { en: "Instead", tr: "-yerine", level: "A2" }, // [cite: 2392]
    { en: "Instruction", tr: "Talimat", level: "A2" }, // [cite: 2392]
    { en: "Instructor", tr: "Eğitmen", level: "A2" }, // [cite: 2392]
    { en: "Instrument", tr: "Enstrüman", level: "A2" }, // [cite: 2392]
    { en: "Intelligent", tr: "Zeki, akıllı", level: "A2" }, // [cite: 2392]
    { en: "International", tr: "Uluslarası", level: "A2" }, // [cite: 2392]
    { en: "Introduction", tr: "Giriş", level: "A2" }, // [cite: 2392]
    { en: "Invent", tr: "İcat etmek", level: "A2" }, // [cite: 2392]
    { en: "Invention", tr: "İcat", level: "A2" }, // [cite: 2392]
    { en: "Invitation", tr: "Davet", level: "A2" }, // [cite: 2392]
    { en: "Invite", tr: "Davet etmek", level: "A2" }, // [cite: 2392]
    { en: "Involve", tr: "İçermek", level: "A2" }, // [cite: 2392]
    { en: "Item", tr: "Madde, öğe, kalem", level: "A2" }, // [cite: 2393]
    { en: "Jam", tr: "Reçel", level: "A2" }, // [cite: 2393]
    { en: "Jazz", tr: "Caz", level: "A2" }, // [cite: 2393]
    { en: "Jewellery", tr: "Mücevherat", level: "A2" }, //
];
